### PR TITLE
Add CPAK format option and show the amount of blocks

### PR DESCRIPTION
**Pull request by Suprapote**
Hello, i added a option to format the controller pak and view how many blocks do you have

### CODE REVIEW

**Comment by networkfusion** [comment]
Hi, thanks for the addition. I have just seen this. I have introduced some conflicts (as did not see this PR) so feel free to resolve and improve them.

**Comment by Suprapote** [comment]
I updated the code. You can merge this, some incompatibilities are because of the messages of mempak format confirmation

**Comment by networkfusion** [comment]
The conflicts remain, so it is not possible to merge. Please finish resolving the conflicts, as I cannot seem to do it (as a maintainer.

image

**Comment by Suprapote** [comment]
I think the only way to do this is applying the changes manually.

**Comment by networkfusion** [comment]
FYI... this seems to show changes being applied to your codebase (rather than mine). Look at the files changed tab...

**Comment by networkfusion** [comment]
try a git rebase on your branch.

**Comment by networkfusion** [comment]
Also, GH seems to be having major issues at my end!

**Comment by Suprapote** [comment]
Fixed, now you can merge 👍

**Comment by networkfusion** [comment]
Thanks for sorting the merge issues.

It seems that the EOF lines have gone missing though. I have added the changes as suggestions.

After a quick review, I would prefer that any attempt to format the CPak is first attempted as a repair. I realise that libdragon dos not really handle it, but needs to be there for when it does.

**Comment by networkfusion** [comment]
As a suggestion (for future PR's), especially when using git... It is always best to branch, rather than commit to the same branch name, as it is much easier to fix merge conflicts etc.

**Pull request closed without merging**
